module.exports.housingOffers = [
    {
        "id": 0,
        "type": "buy",
        "city": "Sadat City",
        "price": 410000,
        "area": 120.0,
        "location": { "long": -91.0, "lat": -22.3 },
        "description": "Lorem ipsum dolor sit am",
    },
    {
        "id": 1,
        "type": "buy",
        "city": "Cairo",
        "price": 220000,
        "area": 93,
        "location": { "long": -91.0, "lat": -22.3 },
        "description": "Lorem ipsum dolor sit am",
    },
    {
        "id": 2,
        "type": "buy",
        "city": "6th October",
        "price": 900000,
        "area": 155,
        "location": { "long": -91.0, "lat": -22.3 },
        "description": "Lorem ipsum dolor sit am",
    },
    {
        "id": 3,
        "type": "rent",
        "city": "Cairo",
        "price": 3000,
        "area": 100,
        "location": { "long": -91.0, "lat": -22.3 },
        "description": "Lorem ipsum dolor sit am",
    },
    {
        "id": 4,
        "type": "rent",
        "city": "Sadat City",
        "price": 1650,
        "area": 72,
        "location": { "long": -91.0, "lat": -22.3 },
        "description": "Lorem ipsum dolor sit am",
    },
    {
        "id": 5,
        "type": "rent",
        "city": "6th October",
        "price": 2400,
        "area": 110,
        "location": { "long": -91.0, "lat": -22.3 },
        "description": "Lorem ipsum dolor sit am",
    },

]