module.exports.services = [
    {
        "id": 0,
        "type": "hospital",
        "city": "Sadat City",
        "name": "Sadat City General Hosptial",
        "location": { "long": -122.2, "lat": 120.0 },
        "hotline": "62318",
    },
    {
        "id": 1,
        "type": "hospital",
        "city": "6th October",
        "name": "Dar Alfouad",
        "location": { "long": 20.2, "lat": -62.0 },
        "hotline": "12323",
    },
    {
        "id": 2,
        "type": "hospital",
        "city": "6th October",
        "name": "Saad Zaghlol",
        "location": { "long": 110.2, "lat": -61.4 },
        "hotline": "66464",
    },
    {
        "id": 3,
        "type": "hospital",
        "city": "Cairo",
        "name": "Alnas",
        "location": { "long": 20.2, "lat": -62.0 },
        "hotline": "12032",
    },
    {
        "id": 4,
        "type": "hospital",
        "city": "Cairo",
        "name": "Aldemerdash",
        "location": { "long": 122.4, "lat": 32.0 },
        "hotline": "34426",
    },
    {
        "id": 5,
        "type": "managerial",
        "city": "6th October",
        "name": "Gehaz Madinet October",
        "location": { "long": 122.4, "lat": 32.0 },
        "hotline": "N/A",
    },
    {
        "id": 6,
        "type": "managerial",
        "city": "Sadat City",
        "name": "Gehaz Madinet AlSadat",
        "location": { "long": 122.4, "lat": 32.0 },
        "hotline": "N/A",
    },
    {
        "id": 7,
        "type": "judge",
        "city": "Sadat City",
        "name": "Sadat City's Court",
        "location": { "long": 122.4, "lat": 32.0 },
        "hotline": "N/A",
    },
    {
        "id": 8,
        "type": "judge",
        "city": "Cairo",
        "name": "Giza's Court",
        "location": { "long": 122.4, "lat": 32.0 },
        "hotline": "N/A",
    },
    {
        "id": 9,
        "type": "pharmacy",
        "city": "Cairo",
        "name": "Elezaby Pharmacies",
        "location": { "long": 124.3, "lat": 35.0 },
        "hotline": "61555",
    },
    {
        "id": 10,
        "type": "pharmacy",
        "city": "6th October",
        "name": "Elezaby Pharmacies",
        "location": { "long": -13.1, "lat": 62.0 },
        "hotline": "61555",
    },
    {
        "id": 11,
        "type": "pharmacy",
        "city": "Sadat City",
        "name": "Dr Sami Farrag pharmacy",
        "location": { "long": -13.1, "lat": 62.0 },
        "hotline": "61512",
    },
    {
        "id": 12,
        "type": "pharmacy",
        "city": "Sadat City",
        "name": "Dr Ahmed Noah pharmacy",
        "location": { "long": -13.1, "lat": 62.0 },
        "hotline": "61512",
    },
    {
        "id": 13,
        "type": "pharmacy",
        "city": "Sadat City",
        "name": "Dr Hesham Azzam pharmacy",
        "location": { "long": -13.1, "lat": 62.0 },
        "hotline": "61512",
    },
]